name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate hashes for static files
        run: |
          # Install required tools
          sudo apt-get install -y jq
          # Temporary file for replacing references
          temp_html=".temp_html"
          # Iterate over static files and rename them with a hash
          find . -type f \( -name "*.css" -o -name "*.js" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.gif" -o -name "*.webp" -o -name "*.webm" \) | while read -r file; do
            # Skip files starting with "bootstrap" for .css and .js
            if [[ "$(basename "$file")" =~ ^bootstrap.*\.(css|js)$ ]]; then
              echo "Skipping file: $file"
              continue
            fi
      
            # Generate a hash based on file content
            hash=$(sha256sum "$file" | awk '{print $1}' | cut -c1-8)
            ext="${file##*.}"
            base="${file%.*}"
            dir=$(dirname "$file")
            new_name="${dir}/$(basename "${base}").${hash}.${ext}"
            
            # Rename the file
            mv "$file" "$new_name"
            echo "Renamed $file to $new_name"
      
            # Update all references in HTML files
            find . -type f -name "*.html" | while read -r html_file; do
              echo "Updating references in $html_file"
              sed -i "s|$(basename "$file")|$(basename "$new_name")|g" "$html_file" || echo "Failed to update $html_file"
            done
      
            # Update all references in CSS files
            find . -type f -name "*.css" | while read -r css_file; do
              sed -i "s|$(basename "$file")|$(basename "$new_name")|g" "$css_file"
            done
      
            # Update all references in JS files
            find . -type f -name "*.js" | while read -r js_file; do
              sed -i "s|$(basename "$file")|$(basename "$new_name")|g" "$js_file"
            done
          done
      
      
      # Configure Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload generated artifacts
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
