name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate hashes for static files
        run: |
          # Find all relevant files excluding bootstrap-prefixed ones
          find . -type f \( -iname '*.css' -o -iname '*.js' -o -iname '*.jpeg' -o -iname '*.jpg' -o -iname '*.png' -o -iname '*.webm' -o -iname '*.webp' \) ! -iname 'bootstrap*' > file_list.txt

          # Generate hashes and rename files
          while IFS= read -r file; do
            hash=$(sha256sum "$file" | cut -d ' ' -f1)
            ext="${file##*.}"
            base="${file%.*}"
            mv "$file" "${base}-$hash.$ext"
          done < file_list.txt

          # Replace references in .css, .html, and .js
          grep -rl --include=\*.{css,html,js} 'bootstrap' . | while read -r ref_file; do
            while IFS= read -r file; do
              ext="${file##*.}"
              base="${file%.*}"
              hash=$(sha256sum "$file" | cut -d ' ' -f1)
              new_file="${base}-$hash.$ext"
              sed -i "s|${file}|${new_file}|g" "$ref_file"
            done < file_list.txt
          done

      # Configure Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload generated artifacts
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
